In [60]:
from cleaning_data import *

dirty_data = load_csv("dirty_dataset.csv")
dirty_data

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,unknown,24-11-23,not_available,NaN,Pandola###,249.72,??,NaN,1,NaN,NaN
1,2824,Fulvio Sismondin/a,fiannuzzi,NaN,09-03-2025,not_available,IT,Acquaron/a,498.08,??,IV59,2,many,yes
2,NaN,Elisa Simeoni??,silvestrirolando@example.com,-5,10/03/2022,05-27-2025,Italia,Campestrinxxx,169.87,Fashion,NaN,4,many,no
3,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,NaN,04-03-24,NaN,NaN,Governolo,77.61,??,NaN,five,NaN,True
4,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,dossettipasquale,NaN,2023-08-19,NaN,Italia,San Vincenzo A Torri,"455,25",Tech,FT44,NaN,715,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50995,8249,Renzo Draghixxx,pier97@example.com,58,13-09-22,NaN,italy,Muriscuvo'NULL,224.03,HOME,NaN,5,NaN,False
50996,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,-5,2023-02-19,NaN,Italy,Ridotti,338.18,??,NaN,five,NaN,True
50997,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,-5,18-10-24,NaN,italy,Grignanon/a,379.41,Tech,NaN,NaN,NaN,no
50998,NaN,Ruggiero Marangoni,roccoborsellino@example.com,unknown,23/08/2025,not_available,italy,Schennan/a,365.38,Home,NaN,5,many,no
50999,3426,Guglielmo Micheletti-Fattori###,ferdinandonaccari@example.org,78,01/01/2023,10-02-2022,Italy,Portosecco,469.38,HOME,TG57,five,many,True

In [61]:
regex = r'^(?![a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$)'
filtered = clean_pattern_column(dirty_data, "user_id", regex)
filtered

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,unknown,24-11-23,not_available,NaN,Pandola###,249.72,??,NaN,1,NaN,NaN
1,NaN,Fulvio Sismondin/a,fiannuzzi,NaN,09-03-2025,not_available,IT,Acquaron/a,498.08,??,IV59,2,many,yes
2,NaN,Elisa Simeoni??,silvestrirolando@example.com,-5,10/03/2022,05-27-2025,Italia,Campestrinxxx,169.87,Fashion,NaN,4,many,no
3,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,NaN,04-03-24,NaN,NaN,Governolo,77.61,??,NaN,five,NaN,True
4,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,dossettipasquale,NaN,2023-08-19,NaN,Italia,San Vincenzo A Torri,"455,25",Tech,FT44,NaN,715,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50995,NaN,Renzo Draghixxx,pier97@example.com,58,13-09-22,NaN,italy,Muriscuvo'NULL,224.03,HOME,NaN,5,NaN,False
50996,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,-5,2023-02-19,NaN,Italy,Ridotti,338.18,??,NaN,five,NaN,True
50997,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,-5,18-10-24,NaN,italy,Grignanon/a,379.41,Tech,NaN,NaN,NaN,no
50998,NaN,Ruggiero Marangoni,roccoborsellino@example.com,unknown,23/08/2025,not_available,italy,Schennan/a,365.38,Home,NaN,5,many,no
50999,NaN,Guglielmo Micheletti-Fattori###,ferdinandonaccari@example.org,78,01/01/2023,10-02-2022,Italy,Portosecco,469.38,HOME,TG57,five,many,True

In [62]:
filtered = delete_na(filtered, "user_id")
filtered.reset_index(drop=True, inplace=True)

In [63]:
filtered = replace_invalid_float(filtered, "purchase_amount")
filtered

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,unknown,24-11-23,not_available,NaN,Pandola###,249.72,??,NaN,1,NaN,NaN
1,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,NaN,04-03-24,NaN,NaN,Governolo,77.61,??,NaN,five,NaN,True
2,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,dossettipasquale,NaN,2023-08-19,NaN,Italia,San Vincenzo A Torri,455.25,Tech,FT44,NaN,715,no
3,bedd5433-0834-44f7-ac07-97c08027a2be,Emma Dibiasixxx,cleliabrambilla@example.com,NaN,11-11-2021,2023/10/29,Italy,Terrasinin/a,99.88,fashion,NaN,3,NaN,yes
4,d5c99441-b19a-4d5f-8261-79e93b7e009a,Anita Volta??,avitturi@example.com,-5,2021-12-05,11-02-24,IT,Mezzolara,387.03,TEC,fB81,4,58,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17097,0d6f55aa-3b6d-4346-9709-9f04b1daf8ab,Aurora Curiel-Canova###,ferrarisronaldo@example.org,21,2024/11/16,not_available,Italia,Umbra,215.96,Home,NaN,3,many,False
17098,03f60bd8-3c8e-4f79-9a9e-b186fe16a042,Priscilla Letta-Capone,amaldiiolanda@example.com,65,2024/12/31,10-14-2021,NaN,Tarzo,433.67,TEC,NaN,3,many,NaN
17099,07380440-2046-4a09-b968-cf0a267885ae,Elmo Mogherini-Perini,vemanuelli@example.com,unknown,2025/08/11,23-05-23,Italy,Bricherasio??,356.81,Tech,NaN,5,NaN,yes
17100,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,-5,2023-02-19,NaN,Italy,Ridotti,338.18,??,NaN,five,NaN,True
17101,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,-5,18-10-24,NaN,italy,Grignanon/a,379.41,Tech,NaN,NaN,NaN,no

In [64]:
filtered = convert_pattern_column(filtered, "purchase_amount", r"free", "0")
filtered

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,unknown,24-11-23,not_available,NaN,Pandola###,249.72,??,NaN,1,NaN,NaN
1,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,NaN,04-03-24,NaN,NaN,Governolo,77.61,??,NaN,five,NaN,True
2,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,dossettipasquale,NaN,2023-08-19,NaN,Italia,San Vincenzo A Torri,455.25,Tech,FT44,NaN,715,no
3,bedd5433-0834-44f7-ac07-97c08027a2be,Emma Dibiasixxx,cleliabrambilla@example.com,NaN,11-11-2021,2023/10/29,Italy,Terrasinin/a,99.88,fashion,NaN,3,NaN,yes
4,d5c99441-b19a-4d5f-8261-79e93b7e009a,Anita Volta??,avitturi@example.com,-5,2021-12-05,11-02-24,IT,Mezzolara,387.03,TEC,fB81,4,58,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17097,0d6f55aa-3b6d-4346-9709-9f04b1daf8ab,Aurora Curiel-Canova###,ferrarisronaldo@example.org,21,2024/11/16,not_available,Italia,Umbra,215.96,Home,NaN,3,many,False
17098,03f60bd8-3c8e-4f79-9a9e-b186fe16a042,Priscilla Letta-Capone,amaldiiolanda@example.com,65,2024/12/31,10-14-2021,NaN,Tarzo,433.67,TEC,NaN,3,many,NaN
17099,07380440-2046-4a09-b968-cf0a267885ae,Elmo Mogherini-Perini,vemanuelli@example.com,unknown,2025/08/11,23-05-23,Italy,Bricherasio??,356.81,Tech,NaN,5,NaN,yes
17100,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,-5,2023-02-19,NaN,Italy,Ridotti,338.18,??,NaN,five,NaN,True
17101,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,-5,18-10-24,NaN,italy,Grignanon/a,379.41,Tech,NaN,NaN,NaN,no

In [65]:
filtered = replace_invalid_int(filtered, "age")
filtered = replace_invalid_int(filtered, "rating")
filtered = replace_invalid_int(filtered, "reviews_count")
filtered

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,unknown,24-11-23,not_available,NaN,Pandola###,249.72,??,NaN,1,NaN,NaN
1,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,NaN,04-03-24,NaN,NaN,Governolo,77.61,??,NaN,five,NaN,True
2,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,dossettipasquale,NaN,2023-08-19,NaN,Italia,San Vincenzo A Torri,455.25,Tech,FT44,NaN,715,no
3,bedd5433-0834-44f7-ac07-97c08027a2be,Emma Dibiasixxx,cleliabrambilla@example.com,NaN,11-11-2021,2023/10/29,Italy,Terrasinin/a,99.88,fashion,NaN,3,NaN,yes
4,d5c99441-b19a-4d5f-8261-79e93b7e009a,Anita Volta??,avitturi@example.com,unknown,2021-12-05,11-02-24,IT,Mezzolara,387.03,TEC,fB81,4,58,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17097,0d6f55aa-3b6d-4346-9709-9f04b1daf8ab,Aurora Curiel-Canova###,ferrarisronaldo@example.org,21,2024/11/16,not_available,Italia,Umbra,215.96,Home,NaN,3,many,False
17098,03f60bd8-3c8e-4f79-9a9e-b186fe16a042,Priscilla Letta-Capone,amaldiiolanda@example.com,65,2024/12/31,10-14-2021,NaN,Tarzo,433.67,TEC,NaN,3,many,NaN
17099,07380440-2046-4a09-b968-cf0a267885ae,Elmo Mogherini-Perini,vemanuelli@example.com,unknown,2025/08/11,23-05-23,Italy,Bricherasio??,356.81,Tech,NaN,5,NaN,yes
17100,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,unknown,2023-02-19,NaN,Italy,Ridotti,338.18,??,NaN,five,NaN,True
17101,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,unknown,18-10-24,NaN,italy,Grignanon/a,379.41,Tech,NaN,NaN,NaN,no

In [66]:
filtered = mean_str_column(filtered, "reviews_count", "many")
filtered = convert_type(filtered, "reviews_count", "Float64")
filtered = convert_type(filtered, "reviews_count", "Int64")

filtered = convert_pattern_column(filtered, "age", np.nan, "unknown")
filtered = mean_str_column(filtered, "age", "unknown")
filtered = convert_type(filtered, "age", "Float64")
filtered = convert_type(filtered, "age", "Int64")
filtered

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,49,24-11-23,not_available,NaN,Pandola###,249.72,??,NaN,1,<NA>,NaN
1,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,49,04-03-24,NaN,NaN,Governolo,77.61,??,NaN,five,<NA>,True
2,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,dossettipasquale,49,2023-08-19,NaN,Italia,San Vincenzo A Torri,455.25,Tech,FT44,NaN,715,no
3,bedd5433-0834-44f7-ac07-97c08027a2be,Emma Dibiasixxx,cleliabrambilla@example.com,49,11-11-2021,2023/10/29,Italy,Terrasinin/a,99.88,fashion,NaN,3,<NA>,yes
4,d5c99441-b19a-4d5f-8261-79e93b7e009a,Anita Volta??,avitturi@example.com,49,2021-12-05,11-02-24,IT,Mezzolara,387.03,TEC,fB81,4,58,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17097,0d6f55aa-3b6d-4346-9709-9f04b1daf8ab,Aurora Curiel-Canova###,ferrarisronaldo@example.org,21,2024/11/16,not_available,Italia,Umbra,215.96,Home,NaN,3,501,False
17098,03f60bd8-3c8e-4f79-9a9e-b186fe16a042,Priscilla Letta-Capone,amaldiiolanda@example.com,65,2024/12/31,10-14-2021,NaN,Tarzo,433.67,TEC,NaN,3,501,NaN
17099,07380440-2046-4a09-b968-cf0a267885ae,Elmo Mogherini-Perini,vemanuelli@example.com,49,2025/08/11,23-05-23,Italy,Bricherasio??,356.81,Tech,NaN,5,<NA>,yes
17100,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,49,2023-02-19,NaN,Italy,Ridotti,338.18,??,NaN,five,<NA>,True
17101,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,49,18-10-24,NaN,italy,Grignanon/a,379.41,Tech,NaN,NaN,<NA>,no

In [67]:
filtered = clean_pattern_column(filtered, "age", "unknown")
filtered = convert_type(filtered, "age", "Int64")

filtered = convert_type(filtered, "purchase_amount", "Float64")

filtered = convert_time(filtered, "signup_date", "mixed")

filtered = clean_pattern_column(filtered, "last_login", r"[a-zA-Z]+")
filtered = convert_time(filtered, "last_login", "mixed")

filtered = convert_pattern_column(filtered, "returned", r"yes", True)
filtered = convert_pattern_column(filtered, "returned", r"no", False)
filtered = clean_pattern_column(filtered, "returned", r"w*")
filtered = convert_type(filtered, "returned", "boolean")

filtered.info()

<class 'pandas.DataFrame'>
RangeIndex: 17102 entries, 0 to 17101
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          17102 non-null  str
 1   name             17102 non-null  str
 2   email            17102 non-null  str
 3   age              17102 non-null  Int64
 4   signup_date      17102 non-null  datetime64[us]
 5   last_login       5723 non-null   datetime64[us]
 6   country          13708 non-null  str
 7   city             17102 non-null  str
 8   purchase_amount  17102 non-null  Float64
 9   category         17102 non-null  str
 10  discount_code    5741 non-null   str
 11  rating           14701 non-null  str
 12  reviews_count    11442 non-null  Int64
 13  returned         6824 non-null   boolean
dtypes: Float64(1), Int64(2), boolean(1), datetime64[us](2), str(8)
memory usage: 1.8 MB

In [68]:
filtered = correct_email(filtered, "email")
filtered

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,49,2023-11-24,NaT,NaN,Pandola###,249.72,??,NaN,1,<NA>,<NA>
1,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,49,2024-04-03,NaT,NaN,Governolo,77.61,??,NaN,five,<NA>,<NA>
2,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,unknown,49,2023-08-19,NaT,Italia,San Vincenzo A Torri,455.25,Tech,FT44,NaN,715,False
3,bedd5433-0834-44f7-ac07-97c08027a2be,Emma Dibiasixxx,cleliabrambilla@example.com,49,2021-11-11,2023-10-29,Italy,Terrasinin/a,99.88,fashion,NaN,3,<NA>,True
4,d5c99441-b19a-4d5f-8261-79e93b7e009a,Anita Volta??,avitturi@example.com,49,2021-12-05,2024-11-02,IT,Mezzolara,387.03,TEC,fB81,4,58,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17097,0d6f55aa-3b6d-4346-9709-9f04b1daf8ab,Aurora Curiel-Canova###,ferrarisronaldo@example.org,21,2024-11-16,NaT,Italia,Umbra,215.96,Home,NaN,3,501,<NA>
17098,03f60bd8-3c8e-4f79-9a9e-b186fe16a042,Priscilla Letta-Capone,amaldiiolanda@example.com,65,2024-12-31,2021-10-14,NaN,Tarzo,433.67,TEC,NaN,3,501,<NA>
17099,07380440-2046-4a09-b968-cf0a267885ae,Elmo Mogherini-Perini,vemanuelli@example.com,49,2025-08-11,2023-05-23,Italy,Bricherasio??,356.81,Tech,NaN,5,<NA>,True
17100,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,49,2023-02-19,NaT,Italy,Ridotti,338.18,??,NaN,five,<NA>,<NA>
17101,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,49,2024-10-18,NaT,italy,Grignanon/a,379.41,Tech,NaN,NaN,<NA>,False

In [69]:
filtered = convert_pattern_column(filtered, "country", r"[Ii][Tt]\w*", "IT")
filtered

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,49,2023-11-24,NaT,NaN,Pandola###,249.72,??,NaN,1,<NA>,<NA>
1,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,49,2024-04-03,NaT,NaN,Governolo,77.61,??,NaN,five,<NA>,<NA>
2,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,unknown,49,2023-08-19,NaT,IT,San Vincenzo A Torri,455.25,Tech,FT44,NaN,715,False
3,bedd5433-0834-44f7-ac07-97c08027a2be,Emma Dibiasixxx,cleliabrambilla@example.com,49,2021-11-11,2023-10-29,IT,Terrasinin/a,99.88,fashion,NaN,3,<NA>,True
4,d5c99441-b19a-4d5f-8261-79e93b7e009a,Anita Volta??,avitturi@example.com,49,2021-12-05,2024-11-02,IT,Mezzolara,387.03,TEC,fB81,4,58,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17097,0d6f55aa-3b6d-4346-9709-9f04b1daf8ab,Aurora Curiel-Canova###,ferrarisronaldo@example.org,21,2024-11-16,NaT,IT,Umbra,215.96,Home,NaN,3,501,<NA>
17098,03f60bd8-3c8e-4f79-9a9e-b186fe16a042,Priscilla Letta-Capone,amaldiiolanda@example.com,65,2024-12-31,2021-10-14,NaN,Tarzo,433.67,TEC,NaN,3,501,<NA>
17099,07380440-2046-4a09-b968-cf0a267885ae,Elmo Mogherini-Perini,vemanuelli@example.com,49,2025-08-11,2023-05-23,IT,Bricherasio??,356.81,Tech,NaN,5,<NA>,True
17100,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,49,2023-02-19,NaT,IT,Ridotti,338.18,??,NaN,five,<NA>,<NA>
17101,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,49,2024-10-18,NaT,IT,Grignanon/a,379.41,Tech,NaN,NaN,<NA>,False

In [70]:
filtered = convert_pattern_column(filtered, "name", r"[^A-Za-z\s]", "")
filtered = convert_pattern_column(filtered, "name", r"([a-zA-Z])\1{2,}", "")
filtered = convert_pattern_column(filtered, "city", r"[^A-Za-z\s]", "")
filtered = convert_pattern_column(filtered, "city", r"([a-zA-Z])\1{2,}", "")
filtered

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardi,pietrobertolucci@example.org,49,2023-11-24,NaT,NaN,Pandola,249.72,??,NaN,1,<NA>,<NA>
1,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellina,rosa95@example.net,49,2024-04-03,NaT,NaN,Governolo,77.61,??,NaN,five,<NA>,<NA>
2,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,unknown,49,2023-08-19,NaT,IT,San Vincenzo A Torri,455.25,Tech,FT44,NaN,715,False
3,bedd5433-0834-44f7-ac07-97c08027a2be,Emma Dibiasi,cleliabrambilla@example.com,49,2021-11-11,2023-10-29,IT,Terrasinina,99.88,fashion,NaN,3,<NA>,True
4,d5c99441-b19a-4d5f-8261-79e93b7e009a,Anita Volta,avitturi@example.com,49,2021-12-05,2024-11-02,IT,Mezzolara,387.03,TEC,fB81,4,58,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17097,0d6f55aa-3b6d-4346-9709-9f04b1daf8ab,Aurora CurielCanova,ferrarisronaldo@example.org,21,2024-11-16,NaT,IT,Umbra,215.96,Home,NaN,3,501,<NA>
17098,03f60bd8-3c8e-4f79-9a9e-b186fe16a042,Priscilla LettaCapone,amaldiiolanda@example.com,65,2024-12-31,2021-10-14,NaN,Tarzo,433.67,TEC,NaN,3,501,<NA>
17099,07380440-2046-4a09-b968-cf0a267885ae,Elmo MogheriniPerini,vemanuelli@example.com,49,2025-08-11,2023-05-23,IT,Bricherasio,356.81,Tech,NaN,5,<NA>,True
17100,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezio,igolino@example.com,49,2023-02-19,NaT,IT,Ridotti,338.18,??,NaN,five,<NA>,<NA>
17101,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,49,2024-10-18,NaT,IT,Grignanona,379.41,Tech,NaN,NaN,<NA>,False

In [71]:
filtered = standarize_text(filtered, "category")
filtered = convert_pattern_column(filtered, "category", r"\btec\b", "tech")
filtered.value_counts(subset=["category"])

category
tech        6353
fashion     4265
home        4245
??          2239
Name: count, dtype: int64

In [72]:
anomaly_quantity(filtered, "category", 3000)

          count
category
??         2239

In [73]:
filtered = one_to_five_from_str(filtered, "rating")
filtered

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardi,pietrobertolucci@example.org,49,2023-11-24,NaT,NaN,Pandola,249.72,??,NaN,1,<NA>,<NA>
1,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellina,rosa95@example.net,49,2024-04-03,NaT,NaN,Governolo,77.61,??,NaN,5,<NA>,<NA>
2,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,unknown,49,2023-08-19,NaT,IT,San Vincenzo A Torri,455.25,tech,FT44,NaN,715,False
3,bedd5433-0834-44f7-ac07-97c08027a2be,Emma Dibiasi,cleliabrambilla@example.com,49,2021-11-11,2023-10-29,IT,Terrasinina,99.88,fashion,NaN,3,<NA>,True
4,d5c99441-b19a-4d5f-8261-79e93b7e009a,Anita Volta,avitturi@example.com,49,2021-12-05,2024-11-02,IT,Mezzolara,387.03,tech,fB81,4,58,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17097,0d6f55aa-3b6d-4346-9709-9f04b1daf8ab,Aurora CurielCanova,ferrarisronaldo@example.org,21,2024-11-16,NaT,IT,Umbra,215.96,home,NaN,3,501,<NA>
17098,03f60bd8-3c8e-4f79-9a9e-b186fe16a042,Priscilla LettaCapone,amaldiiolanda@example.com,65,2024-12-31,2021-10-14,NaN,Tarzo,433.67,tech,NaN,3,501,<NA>
17099,07380440-2046-4a09-b968-cf0a267885ae,Elmo MogheriniPerini,vemanuelli@example.com,49,2025-08-11,2023-05-23,IT,Bricherasio,356.81,tech,NaN,5,<NA>,True
17100,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezio,igolino@example.com,49,2023-02-19,NaT,IT,Ridotti,338.18,??,NaN,5,<NA>,<NA>
17101,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,49,2024-10-18,NaT,IT,Grignanona,379.41,tech,NaN,NaN,<NA>,False